const FALLBACK="my-workspace-fallback";let state=null,remoteVersion=null,saving=false,syncing=false,dragged=null;
const seed={projects:[{id:"p1",name:"Workspace",description:"Das zentrale Projekt für deinen Workspace.",members:1},{id:"p2",name:"Website",description:"Planung und Umsetzung der öffentlichen Website.",members:1},{id:"p3",name:"Interne Tools",description:"Tools und Automatisierungen für das Team.",members:1}],tasks:[{id:"t1",title:"Workspace-Grundgerüst bauen",description:"Navigation, Dashboard und Grundstruktur.",status:"done",priority:"high",projectId:"p1"},{id:"t2",title:"Drag & Drop Kanban",description:"Aufgaben zwischen Status-Spalten verschieben.",status:"progress",priority:"high",projectId:"p1"},{id:"t3",title:"Workspace weiter ausbauen",description:"Weitere Funktionen planen und umsetzen.",status:"todo",priority:"normal",projectId:"p1"},{id:"t4",title:"Design-System definieren",description:"Abstände und Komponenten festlegen.",status:"todo",priority:"normal",projectId:"p2"},{id:"t5",title:"Chat-Konzept",description:"Kanäle und Nachrichten planen.",status:"backlog",priority:"low",projectId:"p3"}],notes:[{id:"n1",title:"Ideen für den Workspace",body:"Hier kannst du Ideen und wichtige Informationen sammeln.",updated:"Heute"}],messages:[{id:"m1",text:"Willkommen im Workspace.",author:"Workspace",time:"gerade eben"}],activity:[{text:"Gemeinsamer Workspace wurde eingerichtet.",time:"gerade eben"}]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const clone=x=>JSON.parse(JSON.stringify(x));
function status(t){return{backlog:"Backlog",todo:"To Do",progress:"In Arbeit",done:"Erledigt"}[t]||t}function pname(id){return state.projects.find(p=>p.id===id)?.name||"Ohne Projekt"}function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function syncMsg(t,ok=true){$("#status").textContent=t;$("#status").style.color=ok?"#25864a":"#c44b4b"}
async function load(){let r=await fetch("/.netlify/functions/workspace?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error(r.status);let p=await r.json();state=p.state;remoteVersion=p.updatedAt;localStorage.setItem(FALLBACK,JSON.stringify(state))}
async function save(){if(saving)return;saving=true;syncMsg("Speichere …");try{let r=await fetch("/.netlify/functions/workspace",{method:"PUT",cache:"no-store",headers:{"Content-Type":"application/json","Cache-Control":"no-cache"},body:JSON.stringify({state})});if(!r.ok)throw Error(r.status);let p=await r.json();remoteVersion=p.updatedAt;localStorage.setItem(FALLBACK,JSON.stringify(state));syncMsg("✓ Gespeichert")}catch(e){console.error(e);localStorage.setItem(FALLBACK,JSON.stringify(state));syncMsg("Speichern fehlgeschlagen",false)}finally{saving=false}}
async function sync(){if(saving||syncing)return;syncing=true;try{let r=await fetch("/.netlify/functions/workspace?v="+Date.now(),{cache:"no-store",headers:{"Cache-Control":"no-cache"}});if(!r.ok)throw Error(r.status);let p=await r.json();if(p.updatedAt!==remoteVersion){state=p.state;remoteVersion=p.updatedAt;localStorage.setItem(FALLBACK,JSON.stringify(state));render();syncMsg("↻ Aktualisiert")}else syncMsg("✓ Synchronisiert")}catch(e){syncMsg("Keine Verbindung",false)}finally{syncing=false}}
function render(){renderProjectsNav();renderStats();renderRecent();renderActivity();renderBoard();renderProjects();renderNotes();renderChat();renderProjectOptions()}
function renderProjectsNav(){$("#projectNav").innerHTML=state.projects.map(p=>`<button class="link" data-p="${p.id}">● ${esc(p.name)}</button>`).join("")}
function renderStats(){$("#sOpen").textContent=state.tasks.filter(t=>t.status!=="done").length;$("#sProgress").textContent=state.tasks.filter(t=>t.status==="progress").length;$("#sDone").textContent=state.tasks.filter(t=>t.status==="done").length;$("#sProjects").textContent=state.projects.length}
function renderRecent(){let a=state.tasks.filter(t=>t.status!=="done").slice(0,7);$("#recent").innerHTML=a.length?a.map(t=>`<div class="taskrow"><div><b>${esc(t.title)}</b><small>${esc(pname(t.projectId))}</small></div><span class="pill ${t.status}">${status(t.status)}</span></div>`).join(""):"<p>Keine offenen Aufgaben.</p>"}
function renderActivity(){$("#activity").innerHTML=state.activity.slice(0,8).map(a=>`<div class="activity">${esc(a.text)}<small>${esc(a.time)}</small></div>`).join("")}
function renderBoard(){let cols=["backlog","todo","progress","done"];$("#kanban").innerHTML=cols.map(c=>{let a=state.tasks.filter(t=>t.status===c);return`<div class="column" data-status="${c}"><div class="columnhead"><b>${status(c)}</b><span class="count">${a.length}</span></div>${a.map(t=>`<div class="card" draggable="true" data-task="${t.id}"><h4>${esc(t.title)}</h4><p>${esc(t.description)}</p><div class="cardfoot"><span>${esc(t.priority)}</span><span>${esc(pname(t.projectId))}</span></div></div>`).join("")}</div>`}).join("");$$('.card').forEach(c=>{c.ondragstart=()=>dragged=c.dataset.task;c.ondragend=()=>dragged=null});$$('.column').forEach(c=>{c.ondragover=e=>{e.preventDefault();c.classList.add('drag')};c.ondragleave=()=>c.classList.remove('drag');c.ondrop=()=>{c.classList.remove('drag');let t=state.tasks.find(x=>x.id===dragged);if(t&&t.status!==c.dataset.status){t.status=c.dataset.status;state.activity.unshift({text:`„${t.title}“ → ${status(t.status)}`,time:"gerade eben"});save().then(render)}}})}
function renderProjects(){$("#projectGrid").innerHTML=state.projects.map(p=>`<div class="project"><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><span class="tag">${state.tasks.filter(t=>t.projectId===p.id).length} Aufgaben</span><span class="tag">Privat</span></div>`).join("")}
function renderNotes(){$("#notesList").innerHTML=state.notes.map(n=>`<div class="noteitem" data-note="${n.id}"><b>${esc(n.title)}</b><small>${esc(n.updated)}</small></div>`).join("");$$('.noteitem').forEach(x=>x.onclick=()=>{let n=state.notes.find(n=>n.id===x.dataset.note);$("#noteTitle").value=n.title;$("#noteBody").value=n.body})}
function renderChat(){$("#messages").innerHTML=state.messages.map(m=>`<div class="message ${m.author==='Du'?'me':''}">${esc(m.text)}<small>${esc(m.author)} · ${esc(m.time)}</small></div>`).join("")}
function renderProjectOptions(){$("#taskProject").innerHTML=state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}
function view(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));let names={dashboard:'Dashboard',board:'Aufgaben',projects:'Projekte',notes:'Notizen',chat:'Chat',settings:'Einstellungen'};$("#crumb").textContent=names[v];$("#title").textContent=v==='dashboard'?'Guten Tag 👋':names[v]}
$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));function openModal(){$("#modal").classList.remove('hidden');$("#taskTitle").focus()}$("#newTask").onclick=$("#heroTask").onclick=$("#boardTask").onclick=openModal;$("#close").onclick=()=>$("#modal").classList.add('hidden');$("#modal").onclick=e=>{if(e.target.id==='modal')$("#modal").classList.add('hidden')};
$("#taskForm").onsubmit=e=>{e.preventDefault();let t={id:'t'+Date.now(),title:$("#taskTitle").value.trim(),description:$("#taskDesc").value.trim(),priority:$("#taskPriority").value,projectId:$("#taskProject").value,status:'todo'};state.tasks.unshift(t);state.activity.unshift({text:`Aufgabe „${t.title}“ erstellt.`,time:'gerade eben'});save().then(()=>{render();$("#modal").classList.add('hidden')})};
function addProject(){let n=prompt('Name des neuen Projekts:');if(!n?.trim())return;state.projects.push({id:'p'+Date.now(),name:n.trim(),description:'Neues Projekt',members:1});state.activity.unshift({text:`Projekt „${n.trim()}“ erstellt.`,time:'gerade eben'});save().then(render)}$("#newProject").onclick=$("#projectTask").onclick=addProject;
$("#saveNote").onclick=()=>{let title=$("#noteTitle").value.trim(),body=$("#noteBody").value.trim();if(!title&&!body)return;state.notes.unshift({id:'n'+Date.now(),title:title||'Unbenannt',body,updated:'gerade eben'});state.activity.unshift({text:`Notiz „${title||'Unbenannt'}“ gespeichert.`,time:'gerade eben'});save().then(()=>{render();$("#noteTitle").value='';$("#noteBody").value=''})};
$("#chatForm").onsubmit=e=>{e.preventDefault();let x=$("#chatInput"),text=x.value.trim();if(!text)return;state.messages.push({id:'m'+Date.now(),text,author:'Du',time:'gerade eben'});save().then(()=>{renderChat();renderActivity()});x.value=''};
$("#syncNow").onclick=sync;$("#reset").onclick=()=>{if(confirm('Demo-Daten wirklich zurücksetzen?')){state=clone(seed);save().then(render)}};
(async()=>{try{await load();syncMsg('✓ Synchronisiert')}catch(e){let raw=localStorage.getItem(FALLBACK);state=raw?JSON.parse(raw):clone(seed);syncMsg('Lokaler Fallback',false)}render();setInterval(sync,2000)})();
