const API='/.netlify/functions/workspace';
const seed={projects:[{id:'p1',name:'Allgemein',description:'Zentrale Aufgaben'},{id:'p2',name:'Website',description:'Website-Projekt'}],tasks:[{id:'t1',title:'Workspace einrichten',status:'done',project:'Allgemein'},{id:'t2',title:'Mobile Ansicht testen',status:'doing',project:'Allgemein'},{id:'t3',title:'Neue Projektidee sammeln',status:'todo',project:'Allgemein'},{id:'t4',title:'Startseite verbessern',status:'backlog',project:'Website'}],notes:[{id:'n1',title:'Willkommen',body:'Deine zentrale Workspace-Notiz.'}],messages:[]};
let state=JSON.parse(localStorage.getItem('workspace-fallback')||'null')||seed,current='dashboard',noteId='n1',saving=false,syncing=false,touch=null;
const pages={dashboard:'Dashboard',tasks:'Aufgaben',projects:'Projekte',notes:'Notizen',chat:'Chat',settings:'Einstellungen'};
const icons={dashboard:'⌂',tasks:'✓',projects:'▦',notes:'✎',chat:'◌',settings:'⚙'};
const $=s=>document.querySelector(s); const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function nav(){return Object.entries(pages).map(([k,v])=>`<button class="nav-btn ${current===k?'active':''}" data-page="${k}">${icons[k]} ${v}</button>`).join('')}
function renderNav(){['#desktopNav','#mobileNav'].forEach(s=>$(s).innerHTML=nav());document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));}
function go(p){if(!pages[p])p='dashboard';current=p;history.pushState({p},'',`#${p}`);closeDrawer();render();scrollTo(0,0)}
onpopstate=()=>{current=location.hash.slice(1)||'dashboard';render()};
function render(){renderNav();$('#headTitle').textContent=pages[current];$('#crumb').textContent=current==='dashboard'?'Workspace':'Workspace / '+pages[current];$('#backBtn').style.visibility=current==='dashboard'?'hidden':'visible';$('#page').innerHTML=({dashboard,tasks,projects,notes,chat,settings}[current])();bind();}
function dashboard(){let open=state.tasks.filter(t=>t.status!=='done').length;return `<div class="page-head"><div><h2>Dein Workspace</h2><p>Alles an einem Ort – auf PC und Handy.</p></div><button class="btn primary" id="quick">＋ Aufgabe</button></div><div class="grid grid4"><div class="card stat"><small>Offene Aufgaben</small><b>${open}</b></div><div class="card stat"><small>Projekte</small><b>${state.projects.length}</b></div><div class="card stat"><small>Notizen</small><b>${state.notes.length}</b></div><div class="card stat"><small>Nachrichten</small><b>${state.messages.length}</b></div></div><div class="grid grid3" style="margin-top:17px"><div class="card panel"><h3>Nächste Aufgaben</h3>${state.tasks.filter(t=>t.status!=='done').slice(0,5).map(t=>`<div class="list-item"><b>${esc(t.title)}</b><small>${esc(t.project||'Allgemein')}</small></div>`).join('')||'<div class="empty">Alles erledigt 🎉</div>'}</div><div class="card panel"><h3>Projekte</h3>${state.projects.map(p=>`<div class="list-item"><b>${esc(p.name)}</b></div>`).join('')}</div><div class="card panel"><h3>Schnellzugriff</h3><div class="actions"><button class="btn" data-page="tasks">Aufgaben</button><button class="btn" data-page="notes">Notizen</button><button class="btn" data-page="chat">Chat</button></div></div></div>`}
const columns=[['backlog','Backlog'],['todo','To Do'],['doing','In Arbeit'],['done','Erledigt']];
function tasks(){return `<div class="page-head"><div><h2>Aufgaben</h2><p>Desktop: ziehen. Handy: Karte gedrückt halten und in eine Spalte ziehen.</p></div><button class="btn primary" id="newTask">＋ Aufgabe</button></div><div class="board">${columns.map(([s,n])=>`<section class="column drop" data-status="${s}"><div class="column-head"><span>${n}</span><span class="count">${state.tasks.filter(t=>t.status===s).length}</span></div><div class="task-list">${state.tasks.filter(t=>t.status===s).map(t=>`<article class="task" draggable="true" data-task="${t.id}"><b>${esc(t.title)}</b><small>${esc(t.project||'Allgemein')}</small></article>`).join('')||'<div class="empty">Leer</div>'}</div></section>`).join('')}</div>`}
function projects(){return `<div class="page-head"><div><h2>Projekte</h2><p>Deine Projekte und Aufgaben im Überblick.</p></div><button class="btn primary" id="newProject">＋ Projekt</button></div><div class="grid grid3">${state.projects.map(p=>`<div class="card project-card"><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><small>${state.tasks.filter(t=>t.project===p.name).length} Aufgaben</small></div>`).join('')}</div>`}
function notes(){let n=state.notes.find(x=>x.id===noteId)||state.notes[0];if(n)noteId=n.id;return `<div class="page-head"><div><h2>Notizen</h2><p>Auch mobil komplett nutzbar.</p></div><button class="btn primary" id="newNote">＋ Notiz</button></div><div class="note-layout"><div class="note-list">${state.notes.map(x=>`<button class="note-choice ${x.id===n?.id?'active':''}" data-note="${x.id}">${esc(x.title)}</button>`).join('')}</div><div class="card panel">${n?`<input class="title-input" id="noteTitle" value="${esc(n.title)}"><textarea class="editor" id="noteBody">${esc(n.body)}</textarea>`:'<div class="empty">Keine Notiz</div>'}</div></div>`}
function chat(){return `<div class="page-head"><div><h2>Chat</h2><p>Kurze Nachrichten im Workspace.</p></div></div><div class="card panel chat"><div class="messages">${state.messages.map(m=>`<div class="message ${m.me?'me':''}">${esc(m.text)}</div>`).join('')||'<div class="empty">Noch keine Nachrichten.</div>'}</div><form class="chat-form" id="chatForm"><input id="chatText" placeholder="Nachricht schreiben…"><button class="btn primary">Senden</button></form></div>`}
function settings(){return `<div class="page-head"><div><h2>Einstellungen</h2><p>Synchronisation des gemeinsamen Workspaces.</p></div></div><div class="card panel"><h3>Synchronisation</h3><p style="color:var(--muted)">Der Datenbestand liegt zentral in Netlify Blobs. Kein eigener Server nötig.</p><button class="btn" id="forceSync">Jetzt synchronisieren</button></div>`}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#quick')?.addEventListener('click',taskModal);$('#newTask')?.addEventListener('click',taskModal);$('#newProject')?.addEventListener('click',projectModal);$('#newNote')?.addEventListener('click',noteModal);$('#forceSync')?.addEventListener('click',sync);document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{noteId=b.dataset.note;render()});let nt=$('#noteTitle'),nb=$('#noteBody');if(nt)nt.oninput=()=>{let n=state.notes.find(x=>x.id===noteId);n.title=nt.value;save()};if(nb)nb.oninput=()=>{let n=state.notes.find(x=>x.id===noteId);n.body=nb.value;save()};let cf=$('#chatForm');if(cf)cf.onsubmit=e=>{e.preventDefault();let i=$('#chatText'),v=i.value.trim();if(v){state.messages.push({text:v,me:true});i.value='';render();save()}};bindDnD()}
function bindDnD(){document.querySelectorAll('.task').forEach(el=>{el.ondragstart=()=>{el.classList.add('dragging');window.dragId=el.dataset.task};el.ondragend=()=>{el.classList.remove('dragging');window.dragId=null};el.addEventListener('touchstart',e=>{touch={id:el.dataset.task,x:e.touches[0].clientX,y:e.touches[0].clientY,moved:false};el.classList.add('dragging')},{passive:true});el.addEventListener('touchmove',e=>{if(!touch)return;let t=e.touches[0],dx=t.clientX-touch.x,dy=t.clientY-touch.y;if(Math.abs(dx)+Math.abs(dy)>8)touch.moved=true;if(!touch.moved)return;e.preventDefault();let z=document.elementFromPoint(t.clientX,t.clientY)?.closest('.drop');document.querySelectorAll('.drop').forEach(x=>x.classList.toggle('drop-active',x===z))},{passive:false});el.addEventListener('touchend',e=>{if(!touch)return;let t=e.changedTouches[0],z=document.elementFromPoint(t.clientX,t.clientY)?.closest('.drop');if(touch.moved&&z)move(touch.id,z.dataset.status);touch=null;el.classList.remove('dragging');document.querySelectorAll('.drop').forEach(x=>x.classList.remove('drop-active'))})});document.querySelectorAll('.drop').forEach(z=>{z.ondragover=e=>{e.preventDefault();z.classList.add('drop-active')};z.ondragleave=()=>z.classList.remove('drop-active');z.ondrop=e=>{e.preventDefault();move(window.dragId,z.dataset.status);z.classList.remove('drop-active')}})}
function move(id,status){let t=state.tasks.find(x=>x.id===id);if(!t)return;t.status=status;render();save()}
function modal(html){$('#modalBox').innerHTML=html;$('#modal').classList.add('open');$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()}}
function closeModal(){$('#modal').classList.remove('open')}
function taskModal(){modal(`<h3>Neue Aufgabe</h3><label>Titel<input id="mTitle" autofocus></label><label>Projekt<select id="mProject">${state.projects.map(p=>`<option>${esc(p.name)}</option>`).join('')}</select></label><div class="modal-actions"><button class="btn" data-close>Abbrechen</button><button class="btn primary" id="mSave">Erstellen</button></div>`);$('#mSave').onclick=()=>{let title=$('#mTitle').value.trim();if(!title)return;state.tasks.push({id:crypto.randomUUID(),title,status:'todo',project:$('#mProject').value});closeModal();render();save()};document.querySelector('[data-close]').onclick=closeModal}
function projectModal(){modal(`<h3>Neues Projekt</h3><label>Name<input id="mName" autofocus></label><div class="modal-actions"><button class="btn" data-close>Abbrechen</button><button class="btn primary" id="mSave">Erstellen</button></div>`);$('#mSave').onclick=()=>{let name=$('#mName').value.trim();if(!name)return;state.projects.push({id:crypto.randomUUID(),name,description:'Neues Projekt'});closeModal();render();save()};document.querySelector('[data-close]').onclick=closeModal}
function noteModal(){modal(`<h3>Neue Notiz</h3><label>Titel<input id="mName" autofocus></label><div class="modal-actions"><button class="btn" data-close>Abbrechen</button><button class="btn primary" id="mSave">Erstellen</button></div>`);$('#mSave').onclick=()=>{let n={id:crypto.randomUUID(),title:$('#mName').value.trim()||'Neue Notiz',body:''};state.notes.push(n);noteId=n.id;closeModal();render();save()};document.querySelector('[data-close]').onclick=closeModal}
$('#menuBtn').onclick=()=>$('#drawer').classList.add('open');$('#drawerShade').onclick=()=>$('#drawer').classList.remove('open');$('#backBtn').onclick=()=>{if(history.length>1)history.back();else go('dashboard')};$('#syncBtn').onclick=sync;
function toast(t){$('#toast').textContent=t}
async function save(){localStorage.setItem('workspace-fallback',JSON.stringify(state));if(saving)return;saving=true;toast('● Speichere…');try{let r=await fetch(API+'?t='+Date.now(),{method:'PUT',headers:{'Content-Type':'application/json','Cache-Control':'no-cache'},cache:'no-store',body:JSON.stringify(state)});if(!r.ok)throw 0;toast('✓ Gespeichert')}catch(e){toast('⚠ Lokal gespeichert')}finally{saving=false}}
async function sync(){if(syncing||saving)return;syncing=true;toast('● Synchronisiere…');try{let r=await fetch(API+'?t='+Date.now(),{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw 0;let x=await r.json();if(x?.tasks){state=x;localStorage.setItem('workspace-fallback',JSON.stringify(state));render()}toast('✓ Synchronisiert')}catch(e){toast('⚠ Offline/Fallback')}finally{syncing=false}}
current=pages[location.hash.slice(1)]?location.hash.slice(1):'dashboard';render();sync();setInterval(sync,2000);
